@Api_HostAddress = https://localhost:7211

GET {{Api_HostAddress}}/api/v1/consultations/ortopedista/2024-09-30
Authorization: Bearer 

###

POST {{Api_HostAddress}}/api/v1/consultations HTTP/1.1
Content-Type: application/json
Authorization: Bearer 

{
    "patientDocument": "12345678912",
    "consultationDate": "2024-09-30T09:00",
    "doctorId": "66e37753a6beddd5679b4caf",
    "specialit": "ortopedista"
}