apiVersion: v1
kind: Namespace
metadata:
  name: medical-consultation
---
apiVersion: v1
kind: Service
metadata:
  name: apigateway-svc
  namespace: medical-consultation
spec:
  selector:
    app: apigateway
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
  namespace: medical-consultation
spec:
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      restartPolicy: Always
      containers:
      - name: apigateway
        image: brianmorais/medical-consultation-api-gateway:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GlobalConfiguration__BaseUrl
          value: http://apigateway-svc
        - name: Routes__0__DownstreamHostAndPorts__0__Host
          value: consultation-api-svc
        - name: Routes__0__DownstreamHostAndPorts__0__Port
          value: '80'
        - name: Routes__1__DownstreamHostAndPorts__0__Host
          value: consultation-api-svc
        - name: Routes__1__DownstreamHostAndPorts__0__Port
          value: '80'
        - name: Routes__2__DownstreamHostAndPorts__0__Host
          value: consultation-api-svc
        - name: Routes__2__DownstreamHostAndPorts__0__Port
          value: '80'
        - name: Routes__3__DownstreamHostAndPorts__0__Host
          value: authentication-api-svc
        - name: Routes__3__DownstreamHostAndPorts__0__Port
          value: '80'
        - name: Routes__4__DownstreamHostAndPorts__0__Host
          value: authentication-api-svc
        - name: Routes__4__DownstreamHostAndPorts__0__Port
          value: '80'
        - name: Routes__5__DownstreamHostAndPorts__0__Host
          value: doctors-api-svc
        - name: Routes__5__DownstreamHostAndPorts__0__Port
          value: '80'
        - name: Routes__6__DownstreamHostAndPorts__0__Host
          value: doctors-api-svc
        - name: Routes__6__DownstreamHostAndPorts__0__Port
          value: '80'
        - name: Routes__7__DownstreamHostAndPorts__0__Host
          value: doctors-api-svc
        - name: Routes__7__DownstreamHostAndPorts__0__Port
          value: '80'
        - name: Routes__8__DownstreamHostAndPorts__0__Host
          value: patients-api-svc
        - name: Routes__8__DownstreamHostAndPorts__0__Port
          value: '80'
        - name: Routes__9__DownstreamHostAndPorts__0__Host
          value: patients-api-svc
        - name: Routes__9__DownstreamHostAndPorts__0__Port
          value: '80'
        - name: Routes__10__DownstreamHostAndPorts__0__Host
          value: patients-api-svc
        - name: Routes__10__DownstreamHostAndPorts__0__Port
          value: '80'
        ports:
        - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: medical-consultation
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: medical-consultation.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: apigateway-svc
            port:
              number: 80