apiVersion: v1
kind: Namespace
metadata:
  name: medical-consultation
---
apiVersion: v1
kind: Service
metadata:
  name: apigateway-svc
  namespace: medical-consultation
spec:
  selector:
    app: apigateway
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
  namespace: medical-consultation
spec:
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      restartPolicy: Always
      containers:
      - name: apigateway
        image: brianmorais/medical-consultation-api-gateway:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GlobalConfigurations__BaseUrl
          value: http://apigateway-svc.medical-consultaion
        - name: Routes__0__DownstreamHostAndPorts__0__Host
          value: consultation-svc.medical-consultaion
        - name: Routes__0__DownstreamHostAndPorts__0__Port
          value: '80'
        - name: Routes__1__DownstreamHostAndPorts__0__Host
          value: consultation-svc.medical-consultaion
        - name: Routes__1__DownstreamHostAndPorts__0__Port
          value: '80'
        - name: Routes__2__DownstreamHostAndPorts__0__Host
          value: consultation-svc.medical-consultaion
        - name: Routes__2__DownstreamHostAndPorts__0__Port
          value: '80'
        - name: Routes__3__DownstreamHostAndPorts__0__Host
          value: authentication-svc.medical-consultaion
        - name: Routes__3__DownstreamHostAndPorts__0__Port
          value: '80'
        - name: Routes__4__DownstreamHostAndPorts__0__Host
          value: authentication-svc.medical-consultaion
        - name: Routes__4__DownstreamHostAndPorts__0__Port
          value: '80'
        - name: Routes__5__DownstreamHostAndPorts__0__Host
          value: doctors-svc.medical-consultaion
        - name: Routes__5__DownstreamHostAndPorts__0__Port
          value: '80'
        - name: Routes__6__DownstreamHostAndPorts__0__Host
          value: doctors-svc.medical-consultaion
        - name: Routes__6__DownstreamHostAndPorts__0__Port
          value: '80'
        - name: Routes__7__DownstreamHostAndPorts__0__Host
          value: doctors-svc.medical-consultaion
        - name: Routes__7__DownstreamHostAndPorts__0__Port
          value: '80'
        - name: Routes__8__DownstreamHostAndPorts__0__Host
          value: patients-svc.medical-consultaion
        - name: Routes__8__DownstreamHostAndPorts__0__Port
          value: '80'
        - name: Routes__9__DownstreamHostAndPorts__0__Host
          value: patients-svc.medical-consultaion
        - name: Routes__9__DownstreamHostAndPorts__0__Port
          value: '80'
        - name: Routes__10__DownstreamHostAndPorts__0__Host
          value: patients-svc.medical-consultaion
        - name: Routes__10__DownstreamHostAndPorts__0__Port
          value: '80'
        ports:
        - containerPort: 80
