apiVersion: v1
kind: Namespace
metadata:
  name: medical-consultation
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: medical-consultation
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: medical-consultation
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        resources:
          limits:
            memory: 100Mi
            cpu: 100m
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: consultation-svc
spec:
  selector:
    app: consultation
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  consultation
  namespace: medical-consultation
  labels:
    app: consultation
spec:
  selector:
    matchLabels:
      app: consultation
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: consultation
    spec:
      containers:
      - name: consultation
        image: brianmorais/medical-consultation-consultation-api:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: AuthSettins__BasicUserName
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: basic-username
        - name: AuthSettins__BasicPassword
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: basic-password
        - name: Redis__ConnectionString
          value: redis-svc
        - name: Services__DoctorUrl
          value: 'http://doctor-svc'
        - name: Services__PatientUrl
          value: 'http://patient-svc'
        - name: Services__AuthUrl
          value: 'http://authentication-svc'
        - name: DatabaseSettings__ConnectionString
          valueFrom:
            secretKeyRef:
              name: databases-secret
              key: consultation
        - name: DatabaseSettings__DatabaseName
          value: medicalAppointmentConsultation
        ports:
        - containerPort: 8080
          name:  consultation