apiVersion: v1
kind: Namespace
metadata:
  name: medical-consultation
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
  namespace: medical-consultation
  labels:
    app: authentication
spec:
  selector:
    matchLabels:
      app: authentication
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
      - name: authentication
        image: brianmorais/medical-consultation-authentication-api:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: PORT
          valeu: '3001'
        - name: DB_CONNECTION
          valueFrom:
            secretKeyRef:
              name: databases-secret
              key: authentication
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: token-secret
        - name: JWT_EXPIRES_IN
          value: '60M'
        - name: BASIC_USERNAME
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: basic-username
        - name: BASIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: basic-password
        ports:
        - containerPort: 3001
          name: authentication