apiVersion: v1
kind: Namespace
metadata:
  name: medical-consultation
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nearby-consultations-rmq
  namespace: medical-consultation
spec:
  selector:
    matchLabels:
      app: nearby-consultations-rmq
  template:
    metadata:
      labels:
        app: nearby-consultations-rmq
    spec:
      containers:
      - name: nearby-consultations-rmq
        image: rabbitmq:3-alpine
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 500Mi
            cpu: 100m
        ports:
        - containerPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: nearby-consultations-rmq-svc
  namespace: medical-consultation
spec:
  selector:
    app: nearby-consultations-rmq
  ports:
  - port: 5672
    targetPort: 5672
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: nearby-consultations
  namespace: medical-consultation
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: nearby-consultations
            image: brianmorais/medical-consultations-nearby-consultations-cron:latest
            env:
            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: databases-secret
                  key: consultation
            - name: DATABASE_NAME
              value: medicalAppointmentConsultation
            - name: COLLECTION_NAME
              value: consultations
            - name: RABBITMQ_CONNECTION
              value: amqp://guest:guest@nearby-consultations-rmq-svc:5672
            - name: EXCHANGE_NAME
              value: medicalConsultation
            - name: QUEUE_NAME
              value: medicalConsultation.queue
            - name: EXCHANGE_SUB
              value: medicalConsultation.sub
          restartPolicy: OnFailure