apiVersion: v1
kind: Namespace
metadata:
  name: medical-consultation
---
apiVersion: v1
kind: Service
metadata:
  name: doctors-api-svc
  namespace: medical-consultation
spec:
  selector:
    app: doctors-api
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctors-api
  namespace: medical-consultation
  labels:
    app: doctors-api
spec:
  selector:
    matchLabels:
      app: doctors-api
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: doctors-api
    spec:
      restartPolicy: Always
      containers:
      - name: doctors-api
        image: brianmorais/medical-consultation-doctors-api:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: PORT
          value: '3000'
        - name: DB_CONNECTION
          valueFrom:
            secretKeyRef:
              name: databases-secret
              key: doctors
        - name: AUTH_URL
          value: 'http://authentication-svc'
        ports:
        - containerPort: 3000