name: Docker Image ApiGateway
on:
  push:
    branches:
      - main
    paths:
      - 'MedicalConsultation.ApiGateway/**'
  workflow_dispatch:
    
jobs:

  build-and-publish:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.1.1

    - name: Login to Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: 'brianmorais'
        password: ${{ secrets.MEDICAL_CONSULTATION_DOCKER }}

    - name: Set Build Date
      run: echo "BUILD_DATE=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

    - name: Build and push Docker images
      uses: docker/build-push-action@v5.1.0
      with:
        push: true
        context: 'MedicalConsultation.ApiGateway'
        file: 'MedicalConsultation.ApiGateway/Dockerfile'
        tags: |
          brianmorais/medical-consultation-api-gateway:v${{ env.BUILD_DATE }}
          brianmorais/medical-consultation-api-gateway:latest