name: Docker Image Authentication.Api
on:
  push:
    branches:
      - main
    paths:
      - 'MedicalConsultation.Authentication.Api/**'
  workflow_dispatch:
    
jobs:

  build-and-publish:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.1.1

    - name: Login to Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: 'brianmorais'
        password: ${{ secrets.MEDICAL_CONSULTATION_DOCKER }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v5.1.0
      with:
        push: true
        context: 'MedicalConsultation.Authentication.Api/Dockerfile'
        tags: |
          brianmorais/projetoexemploaspnet:v${{ github.run_number }}
          brianmorais/projetoexemploaspnet:latest